baseURL = "https://shirocoop.xyz"
languageCode = "en-us"
title = "Shiro co-op"
theme = "paper"

[params]
  description = "Shiro is a local first supply chain network on a mission to create thriving regenerative food systems. A multi stakeholder platform cooperative – open source, co-owned by all active participants."
  images = ["/Distributed_Network.png"]
  title = "Shiro co-op"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -200

  [[menu.main]]
    identifier = "discourse"
    name = ""
    pre = "<i class='fab fa-discourse'></i>"
    url = "https://foodshift.se/c/workspaces/shiro/37"
    weight = -110

  [[menu.main]]
    identifier = "medium"
    name = ""
    pre = "<i class='fab fa-medium'></i>"
    url = "https://medium.com/shirocoop"
    weight = -110

  [[menu.main]]
    identifier = "twitter"
    name = ""
    pre = "<i class='fab fa-twitter'></i>"
    url = "https://twitter.com/shiro_coop"
    weight = -110

  [[menu.main]]
    identifier = "telegram"
    name = ""
    pre = "<i class='fab fa-telegram'></i>"
    url = "https://t.me/shirocoop"
    weight = -110

  [[menu.main]]
    identifier = "github"
    name = ""
    pre = "<i class='fab fa-github'></i>"
    url = "https://github.com/shirocoop"
    weight = -110
